"""Pruebas de resolución de título (OCR / fallback limpio)."""

from pathlib import Path

from backend.app.pipeline import _clean_fallback, _title_from_musicxml


def _write(tmp_path, name, xml):
    p = tmp_path / name
    p.write_text(xml, encoding="utf-8")
    return p


def test_ocr_title_from_largest_credit_words(tmp_path):
    xml = (
        '<score-partwise>'
        '<credit><credit-words font-size="8">pág 1</credit-words></credit>'
        '<credit><credit-words font-size="24">Cantad Alegres al Señor</credit-words></credit>'
        '</score-partwise>'
    )
    p = _write(tmp_path, "a.musicxml", xml)
    assert _title_from_musicxml(p) == "Cantad Alegres al Señor"


def test_ocr_skips_filename_like_work_title(tmp_path):
    xml = (
        '<score-partwise><work><work-title>himno3.jpg</work-title></work>'
        '<credit><credit-words font-size="20">Alma Bendice al Señor</credit-words></credit>'
        '</score-partwise>'
    )
    p = _write(tmp_path, "b.musicxml", xml)
    assert _title_from_musicxml(p) == "Alma Bendice al Señor"


def test_clean_fallback_drops_autogenerated_names():
    assert _clean_fallback("Screenshot_2026-06-15 Chrome") == "Himno sin título"
    assert _clean_fallback("IMG_1234") == "Himno sin título"
    assert _clean_fallback("DSC09823") == "Himno sin título"


def test_clean_fallback_humanizes_real_names():
    assert _clean_fallback("castillo_fuerte") == "castillo fuerte"
    assert _clean_fallback("Cantad") == "Cantad"


def test_prepare_image_inverts_dark_mode(tmp_path):
    from PIL import Image, ImageStat
    from backend.app.omr import _prepare_image

    # Imagen "modo oscuro": fondo negro con una marca blanca.
    dark = Image.new("RGB", (2500, 1200), (0, 0, 0))
    for x in range(100, 400):
        for y in range(100, 300):
            dark.putpixel((x, y), (255, 255, 255))
    src = tmp_path / "dark.png"
    dark.save(src)

    out = _prepare_image(src, tmp_path / "omr")
    assert out != src  # se procesó
    mean = ImageStat.Stat(Image.open(out).convert("L")).mean[0]
    assert mean > 150  # ahora es fondo claro (invertida)
